### PR TITLE
Display version information in a dialog

### PR DESCRIPTION
**Pull request by claudio-walser**
Hi there, I've added the functionality, mentionend in [Issue #2](https://github.com/DCS-Skunkworks/Bort/issues/2)

Hope this is sufficient and what you had in mind.

### CODE REVIEW

**Comment by charliefoxtwo** [comment]
I don't know that I had anything specific in mind for this feature. Could you include a screenshot of how this looks? Otherwise seems fine to me!

**Comment by claudio-walser** [comment]
Sure, I took one in both color modes, accelerator shortcut working as well. What is a little ugly is the fact that you can open the dialog multiple times. 
image
image

**Comment by claudio-walser** [comment]
dialog.showMessageBoxSync would fix the multiple dialog issue, but since it does not return a promise, there is no exception handling. Not quite sure what would happen in case of an error. I'll kindly let the decision to you ;)

Then on the other hand, the file open dialog opens multiple times as well 🤷

**Comment by charliefoxtwo** [comment]
Heh, the file dialog issue definitely sounds like a bug thst should be fixed at some point.

**Pull request merged**
